### ISSUE TITLE
wrong results of simplr::simplifyq

### ISSUE THREAD

**Issue by cezden** [oflasch/simplr#1]
When simplifying expression (a/y^3 + b/y^3) strange things happen:

> simplr::simplifyq(0/y^3 + 0/y^3)
> [1] 0
> simplr::simplifyq(1/y^3 + 1/y^3)
> 2 \* (1/y^3)
> simplr::simplifyq(2/y^3 + 2/y^3)
> 2 \* (2/y^3)
> **> simplr::simplifyq(1/y^3 + 2/y^3)
> 2 \* (1/y^3)**
> **> simplr::simplifyq(2/y^3 + 1/y^3)
> 2 \* (2/y^3)**
> **> simplr::simplifyq(1/y^3 + 3/y^3)
> 2 \* (1/y^3)**
> **>   simplr::simplifyq(3/y^3 + 1/y^3)
> 2 \* (3/y^3)**
> **> simplr::simplifyq(3/(y^3) + 1/(y^3))
> 2 \* (3/y^3)**
> **>   simplr::simplifyq(1/y^3 + 10/y^3)
> 2 \* (1/y^3)**
> **>   simplr::simplifyq(10/y^3 + 1/y^3)
> 2 \* (10/y^3)**
> 
> sessionInfo(package = "simplr")
> R version 3.3.1 (2016-06-21)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
character(0)

other attached packages:
[1] simplr_0.1-1

loaded via a namespace (and not attached):
 [1] rsconnect_0.4.3    graphics_3.3.1     tools_3.3.1        utils_3.3.1        grDevices_3.3.1  
 [6] stats_3.3.1        datasets_3.3.1     ExpFamilyLab_0.1.0 methods_3.3.1      base_3.3.1

**Comment by oflasch** [comment]
Many thanks for the report. I'm looking into it.

**Comment by oflasch** [comment]
We just fixed a bug in the underlying ev3 CAS solving this issue. We also added new test cases. @cezden It would be great if you could validate our fix, so that we can push an update to CRAN.

**Comment by cezden** [comment]
I've just built&checked the fix with the following results:
[during the CRAN check (make check)]
- checking compiled code ... WARNING
  File ‘simplr/libs/simplr.so’:
  Found ‘___assert_rtn’, possibly from ‘assert’ (C)
    Objects: ‘expression.o’, ‘fastexpression.o’, ‘r_interface.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor the system RNG.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.

**Comment by cezden** [comment]
I've just built&checked the fix with the following results:
[testing the package (./run-tests)]
1. Failure: advanced simplification works (@test-simplify.R#31) ----------------
   s(1/y^3 + 2/y^3) not equal to u(1/y^3 + 2/y^3).
   target, current do not match when deparsed
2. Failure: advanced simplification works (@test-simplify.R#32) ----------------
   s(2/y^3 + 1/y^3) not equal to u(2/y^3 + 1/y^3).
   target, current do not match when deparsed
3. Failure: advanced simplification works (@test-simplify.R#33) ----------------
   s(1/y^3 + 3/y^3) not equal to u(1/y^3 + 3/y^3).
   target, current do not match when deparsed
4. Failure: advanced simplification works (@test-simplify.R#34) ----------------
   s(3/y^3 + 1/y^3) not equal to u(3/y^3 + 1/y^3).
   target, current do not match when deparsed
5. Failure: advanced simplification works (@test-simplify.R#35) ----------------
   s(3/(y^3) + 1/(y^3)) not equal to u(3/y^3 + 1/y^3).
   target, current do not match when deparsed
6. Failure: advanced simplification works (@test-simplify.R#36) ----------------
   s(1/y^3 + 10/y^3) not equal to u(1/y^3 + 10/y^3).
   target, current do not match when deparsed
7. Failure: advanced simplification works (@test-simplify.R#37) ----------------
   s(10/y^3 + 1/y^3) not equal to u(10/y^3 + 1/y^3).
   target, current do not match when deparsed
8. Failure: advanced simplification works (@test-simplify.R#39) ----------------
   s(1/y^3 - 2/y^3) not equal to u(1/y^3 + -(2/y^3)).
   Types not compatible: double vs language

testthat results ================================================================
OK: 18 SKIPPED: 0 FAILED: 8
1. Failure: advanced simplification works (@test-simplify.R#31) 
2. Failure: advanced simplification works (@test-simplify.R#32) 
3. Failure: advanced simplification works (@test-simplify.R#33) 
4. Failure: advanced simplification works (@test-simplify.R#34) 
5. Failure: advanced simplification works (@test-simplify.R#35) 
6. Failure: advanced simplification works (@test-simplify.R#36) 
7. Failure: advanced simplification works (@test-simplify.R#37) 
8. Failure: advanced simplification works (@test-simplify.R#39) 

Error: testthat unit tests failed

**Comment by cezden** [comment]
Thank you for the blazingly fast fix 👍 
I've checked the test cases and they seem to work (yet the last one - (@test-simplify.R#39) - is a bit bizzare: 'Types not compatible: double vs language').
